#
# Module manifest for module 'PSGet_IntuneDocumentation'
#
# Generated by: Thomas Kurth
#
# Generated on: 29.01.2020
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'IntuneDocumentation.psm1'

# Version number of this module.
ModuleVersion = '2.0.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '10231a0d-b6a4-2a17-a726-e3b223ad0aa9'

# Author of this module
Author = 'Thomas Kurth'

# Company or vendor of this module
CompanyName = 'WorkplaceNinjas'

# Copyright statement for this module
Copyright = '(c) 2020 Thomas Kurth. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Automatic Intune Documentation to simplify the life of admins and consultants.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @('Microsoft.Graph.Intune', 
               'PSWord')

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Invoke-IntuneDocumentation'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Intune','Windows','Documentation','MEM','MSGraph'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/ThomasKur/IntuneDocumentation/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/ThomasKur/IntuneDocumentation'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/ThomasKur/ModernWorkplaceClientCenter/master/Logo/MWCC-Logo-512.png'

        # ReleaseNotes of this module
        ReleaseNotes = ' 2.0.0 - 29.01.2020 - Thomas Kurth

- Migrated to PSModule
- Published to PSGallery



 To see the complete history, checkout the Release Notes on Github'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        ExternalModuleDependencies = @('PSWord','Microsoft.Intune.Graph')

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

